version: '3.8'

services:
  rwad_furas_database:
    image: postgres:17-alpine
    container_name: rwad_furas_database_dev
    environment:
      POSTGRES_DB: rwad_furas_db_dev
      POSTGRES_USER: rwad_furas_user
      POSTGRES_PASSWORD: rwad_furas_dev_password
    volumes:
      - rwad_furas_postgres_dev_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - rwad_furas_dev_network
    restart: unless-stopped

  rwad_furas_redis:
    image: redis:8.0-alpine
    container_name: rwad_furas_redis_dev
    command: redis-server --requirepass rwad_furas_dev_redis_password
    volumes:
      - rwad_furas_redis_dev_data:/data
    ports:
      - "6380:6379"
    networks:
      - rwad_furas_dev_network
    restart: unless-stopped

  rwad_furas_backend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: rwad_furas_backend_dev
    environment:
      - DJANGO_SETTINGS_MODULE=core.settings.development
      - POSTGRES_HOST=rwad_furas_database
      - POSTGRES_USER=rwad_furas_user
      - POSTGRES_PASSWORD=rwad_furas_dev_password
      - POSTGRES_NAME=rwad_furas_db_dev
      - REDIS_HOST=rwad_furas_redis
      - REDIS_PASSWORD=rwad_furas_dev_redis_password
    volumes:
      # 🔥 LIVE CODE RELOADING - Mount your entire project
      - .:/app
      - /app/.venv  # Exclude virtual environment
      # Don't mount staticfiles - let Django handle it internally
      - ./media:/app/media
    ports:
      - "8000:8000"
    depends_on:
      - rwad_furas_database
      - rwad_furas_redis
    networks:
      - rwad_furas_dev_network
    restart: unless-stopped
    # Override entrypoint to skip collectstatic in development
    entrypoint: []
    command: >
      bash -c "
        echo '🚀 Starting Development Server...'
        source .venv/bin/activate
        python manage.py migrate --noinput
        python manage.py runserver 0.0.0.0:8000
      "

  rwad_furas_celery_worker:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: rwad_furas_celery_worker_dev
    environment:
      - DJANGO_SETTINGS_MODULE=core.settings.development
      - POSTGRES_HOST=rwad_furas_database
      - POSTGRES_USER=rwad_furas_user
      - POSTGRES_PASSWORD=rwad_furas_dev_password
      - POSTGRES_NAME=rwad_furas_db_dev
      - REDIS_HOST=rwad_furas_redis
      - REDIS_PASSWORD=rwad_furas_dev_redis_password
    volumes:
      # 🔥 LIVE CODE RELOADING for Celery too
      - .:/app
      - /app/.venv
    depends_on:
      - rwad_furas_database
      - rwad_furas_redis
    networks:
      - rwad_furas_dev_network
    restart: unless-stopped
    # Override entrypoint for Celery - no static files needed
    entrypoint: []
    command: >
      bash -c "
        echo '🔄 Starting Celery Worker...'
        source .venv/bin/activate
        celery -A core worker --loglevel=info --concurrency=2
      "

volumes:
  rwad_furas_postgres_dev_data:
  rwad_furas_redis_dev_data:

networks:
  rwad_furas_dev_network:
    driver: bridge
