version: '3.8'

services:
  rwad_furas_database:
    image: postgres:17-alpine
    container_name: rwad_furas_database
    environment:
      POSTGRES_DB: rwad_furas_db
      POSTGRES_USER: rwad_furas_user
      POSTGRES_PASSWORD: rwad_furas_password_2025
    volumes:
      - rwad_furas_postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - rwad_furas_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U rwad_furas_user -d rwad_furas_db"]
      interval: 30s
      timeout: 10s
      retries: 3

  rwad_furas_redis:
    image: redis:8.0-alpine
    container_name: rwad_furas_redis
    command: redis-server --requirepass rwad_furas_redis_password_2025
    volumes:
      - rwad_furas_redis_data:/data
    ports:
      - "6379:6379"
    networks:
      - rwad_furas_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  rwad_furas_backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rwad_furas_backend
    environment:
      - DJANGO_SETTINGS_MODULE=core.settings.production
    volumes:
      - ./media:/app/media
      - ./staticfiles:/app/staticfiles
    depends_on:
      rwad_furas_database:
        condition: service_healthy
      rwad_furas_redis:
        condition: service_healthy
    networks:
      - rwad_furas_network
    restart: unless-stopped
    expose:
      - "8000"

  rwad_furas_celery_worker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rwad_furas_celery_worker
    command: celery -A core worker --loglevel=info --concurrency=4
    environment:
      - DJANGO_SETTINGS_MODULE=core.settings.production
    volumes:
      - ./media:/app/media
    depends_on:
      rwad_furas_database:
        condition: service_healthy
      rwad_furas_redis:
        condition: service_healthy
    networks:
      - rwad_furas_network
    restart: unless-stopped

  rwad_furas_nginx:
    image: nginx:1.27-alpine
    container_name: rwad_furas_nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./config/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./staticfiles:/app/staticfiles:ro
      - ./media:/app/media:ro
      - ./config/ssl:/etc/nginx/ssl:ro
    depends_on:
      - rwad_furas_backend
    networks:
      - rwad_furas_network
    restart: unless-stopped

volumes:
  rwad_furas_postgres_data:
    driver: local
  rwad_furas_redis_data:
    driver: local

networks:
  rwad_furas_network:
    driver: bridge
